version: "3.9"

services:
  backend:
    build:
      context: ./backend/zoeacount
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/zoeacount:/app
      - /usr/lib:/usr/lib
      - /usr/share/libcamera:/usr/share/libcamera
      - /run/udev:/run/udev:ro
    privileged: true
    devices:
      - "/dev:/dev"
    environment:
      - LD_LIBRARY_PATH=/usr/lib
      - LIBCAMERA_LOG_LEVELS=3
    networks:
      - zoeacount
    mem_limit: 512m 
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart:
      on-failure
    ports:
      - "3000:3000"
    networks:
      - zoeacount


networks:
  zoeacount:
    driver: bridge