version: "3.9"

services:
  backend:
    build:
      context: ./backend/my_app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/my_app/my_app/.env
    networks:
      - zoeacount

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - zoeacount

  nginx:
    restart: always
    depends_on:
      - backend
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - zoeacount

networks:
  zoeacount:
    driver: bridge