version: "3.9"

services:
  backend:
    build:
      context: ./backend/zoeacount
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/zoeacount:/app
    networks:
      - zoeacount

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart:
      on-failure
    ports:
      - "3000:3000"
    networks:
      - zoeacount


networks:
  zoeacount:
    driver: bridge