# Generated by Django 4.2.17 on 2025-02-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoeaBatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('batch', models.IntegerField(blank=True, default=0, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_phase', models.IntegerField(blank=True, default=0, null=True)),
                ('count_data', models.IntegerField(default=0)),
                ('mortality_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZoeaTable',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('batch', models.IntegerField(blank=True, default=0, null=True)),
                ('img_blob', models.ImageField(default=None, upload_to='')),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('megalopa_datestamp', models.DateField(auto_now_add=True)),
                ('count_data', models.IntegerField(default=0)),
                ('captured_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
