# Generated by Django 5.1.3 on 2024-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZoeaTable",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("img_blob", models.BinaryField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("count_data", models.IntegerField(default=0)),
                ("mortality_rate", models.FloatField(default=0)),
                ("cumulative_mortality_rate", models.FloatField(default=0)),
            ],
        ),
    ]
