# Generated by Django 4.2.17 on 2025-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoeaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoeatable',
            name='megalopa_datestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
