# Generated by Django 4.2.16 on 2024-11-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zoeaapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoeatable",
            name="age",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="zoeatable",
            name="phase",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="zoeatable",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="zoeatable",
            name="img_blob",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
