# Generated by Django 4.2.17 on 2025-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoeaapi', '0002_alter_zoeatable_megalopa_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoeatable',
            name='megalopa_datestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
